language: node_js
node_js:
  - "10.20.1"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - xvfb
      - libsecret-1-dev

before_install:
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0';
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3;
    fi

install:
  - npm ci

script:
  - npm test