sudo: false

language: node_js
node_js:
  - "5"

os:
  - linux

env:
  - CODE_TESTS_PATH="$TRAVIS_BUILD_DIR/out/test"
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run compile
  - npm run vscode:prepublish

script:
  - npm test
