# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Visual Studio Code Tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # additional packages for linux
    - name: install packages (linux)
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'

    - name: npm clean install
      run: npm ci

    - name: vscode tests (windows or mac)
      run: npm test
      if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'

    - name: vscode tests (linux)
      run: xvfb-run --auto-servernum npm test
      if: matrix.os == 'ubuntu-latest'